inherit_from: rubocop-suse.yml

AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'vendor/**/*'
    - '.git/**/*'
    - lib/lignite/ev3_ops.rb

Naming/FileName:
  Exclude:
    - spec/data/*.rb

Layout/IndentHeredoc:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# self.sleep is Ev3Ops#sleep, sleep is Kernel#sleep
Style/RedundantSelf:
  Exclude:
    - spec/data/*.rb

Metrics/BlockLength:
  Exclude:
    - lignite.gemspec
    - lib/lignite/ev3_tool.rb
    - spec/**/*.rb

Metrics/ClassLength:
  Max: 120
  Exclude:
    - lib/lignite/ev3_tool.rb
    - lib/lignite/motors.rb

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Exclude:
    # generated
    - lib/lignite/enums.rb
