inherit_from: rubocop-suse.yml

AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'vendor/**/*'
    - '.git/**/*'
    - lib/lignite/ev3_ops.rb

Naming/FileName:
  Exclude:
    - spec/data/*.rb

Layout/IndentHeredoc:
  EnforcedStyle: unindent
  Exclude:
    - lignite.gemspec

Performance/RedundantBlockCall:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - lignite.gemspec
    - spec/**/*.rb

Metrics/ClassLength:
  Exclude:
    - lib/lignite/motors.rb

Metrics/MethodLength:
  Max: 20
