inherit_from: rubocop-suse.yml

AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'vendor/**/*'
    - '.git/**/*'
    - lib/lignite/ev3_ops.rb

Naming/FileName:
  Exclude:
    - spec/data/*.rb

Layout/IndentHeredoc:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - lignite.gemspec
    - bin/ev3tool
    - spec/**/*.rb

Metrics/ClassLength:
  Exclude:
    - bin/ev3tool
    - lib/lignite/motors.rb

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Exclude:
    # generated
    - lib/lignite/enums.rb
